Traceback (most recent call last):
  File "C:\Programming\rl_cooperation\lib\site-packages\gym\envs\registration.py", line 121, in spec
    return self.env_specs[id]
KeyError: 'SpaceCannon-v1'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "c:\Programming\rl_cooperation\Pygame_RL_cooperation\Algorithm\DQN_SpaceCannons\agent.PY", line 306, in <module>
    main(False)
  File "c:\Programming\rl_cooperation\Pygame_RL_cooperation\Algorithm\DQN_SpaceCannons\agent.PY", line 103, in main
    env = gym.make("Space_cannons:SpaceCannon-v1")
  File "C:\Programming\rl_cooperation\lib\site-packages\gym\envs\registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "C:\Programming\rl_cooperation\lib\site-packages\gym\envs\registration.py", line 89, in make
    spec = self.spec(path)
  File "C:\Programming\rl_cooperation\lib\site-packages\gym\envs\registration.py", line 129, in spec
    raise error.DeprecatedEnv('Env {} not found (valid versions include {})'.format(id, matching_envs))
gym.error.DeprecatedEnv: Env SpaceCannon-v1 not found (valid versions include ['SpaceCannon-v5'])