pygame 2.0.1 (SDL 2.0.14, Python 3.9.7)
Hello from the pygame community. https://www.pygame.org/contribute.html
initial setup complete
initial setup complete










































1801it [01:49, 23.05it/s]
1801it [01:49, 23.05it/s]Traceback (most recent call last):
  File "C:\Users\Shizu\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Shizu\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\Shizu\.vscode\extensions\ms-python.python-2021.9.1191016588\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\Shizu\.vscode\extensions\ms-python.python-2021.9.1191016588\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\Shizu\.vscode\extensions\ms-python.python-2021.9.1191016588\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\Shizu\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Shizu\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Shizu\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Programming\rl_cooperation\Pygame_RL_cooperation\Algorithm\DQN_SpaceCannons\agent.PY", line 311, in <module>
    #main(True, pth) add model to test
  File "c:\Programming\rl_cooperation\Pygame_RL_cooperation\Algorithm\DQN_SpaceCannons\agent.PY", line 284, in main
    'test_video': wandb.Video(frames.transpose(0, 3, 1, 2), "Test_performance", fps = 25, format = 'mp4',)
  File "<__array_function__ internals>", line 5, in mean
  File "C:\Programming\rl_cooperation\lib\site-packages\numpy\core\fromnumeric.py", line 3440, in mean
    return _methods._mean(a, axis=axis, dtype=dtype,
  File "C:\Programming\rl_cooperation\lib\site-packages\numpy\core\_methods.py", line 167, in _mean
    rcount = _count_reduce_items(arr, axis, keepdims=keepdims, where=where)
  File "C:\Programming\rl_cooperation\lib\site-packages\numpy\core\_methods.py", line 76, in _count_reduce_items
    items *= arr.shape[mu.normalize_axis_index(ax, arr.ndim)]
numpy.AxisError: axis -103 is out of bounds for array of dimension 0