pygame 2.0.1 (SDL 2.0.14, Python 3.9.7)
Hello from the pygame community. https://www.pygame.org/contribute.html
initial setup complete
initial setup complete
Traceback (most recent call last):
  File "C:\Programming\rl_cooperation\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'COMPLETE_COOP_kill'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\Shizu\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Shizu\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\Shizu\.vscode\extensions\ms-python.python-2021.9.1218897484\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\Shizu\.vscode\extensions\ms-python.python-2021.9.1218897484\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\Shizu\.vscode\extensions\ms-python.python-2021.9.1218897484\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\Shizu\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Shizu\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Shizu\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Programming\rl_cooperation\Pygame_RL_cooperation\Algorithm\DQN_SpaceCannons\agent.PY", line 315, in <module>
    main(False)
  File "c:\Programming\rl_cooperation\Pygame_RL_cooperation\Algorithm\DQN_SpaceCannons\agent.PY", line 202, in main
    observation, reward, done, info = env.step([action1,action2])
  File "c:\Programming\rl_cooperation\Pygame_RL_cooperation\Algorithm\DQN_SpaceCannons\utils.py", line 27, in step
    image, reward, done,  info = self.env.step(action)
  File "c:\programming\rl_cooperation\pygame_rl_cooperation\spacecannons\SpaceCannons\envs\SpaceCannons.py", line 263, in step
    self.COMPLETE_COOP_kill+=interdf['COMPLETE_COOP_kill']
  File "C:\Programming\rl_cooperation\lib\site-packages\pandas\core\frame.py", line 3455, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Programming\rl_cooperation\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'COMPLETE_COOP_kill'