2021-09-11 12:44:37,251 INFO    MainThread:10176 [internal.py:wandb_internal():86] W&B internal server running at pid: 10176, started at: 2021-09-11 12:44:37.242182
2021-09-11 12:44:37,253 INFO    WriterThread:10176 [datastore.py:open_for_write():77] open: C:\Programming\rl_cooperation\Pygame_RL_cooperation\wandb\offline-run-20210911_124436-6rxfhcbl\run-6rxfhcbl.wandb
2021-09-11 12:44:37,253 DEBUG   HandlerThread:10176 [handler.py:handle_request():126] handle_request: run_start
2021-09-11 12:44:37,270 DEBUG   HandlerThread:10176 [meta.py:__init__():40] meta init
2021-09-11 12:44:37,270 DEBUG   HandlerThread:10176 [meta.py:__init__():54] meta init done
2021-09-11 12:44:37,271 DEBUG   HandlerThread:10176 [meta.py:probe():211] probe
2021-09-11 12:44:37,335 DEBUG   HandlerThread:10176 [git.py:repo():33] git repository is invalid
2021-09-11 12:44:37,335 DEBUG   HandlerThread:10176 [meta.py:_save_pip():58] save pip
2021-09-11 12:44:37,335 DEBUG   HandlerThread:10176 [meta.py:_save_pip():72] save pip done
2021-09-11 12:44:37,335 DEBUG   HandlerThread:10176 [meta.py:probe():249] probe done
2021-09-11 12:44:53,341 WARNING MainThread:10176 [internal.py:wandb_internal():145] Internal process interrupt: 1
2021-09-11 12:44:53,501 WARNING MainThread:10176 [internal.py:wandb_internal():145] Internal process interrupt: 2
2021-09-11 12:44:53,501 ERROR   MainThread:10176 [internal.py:wandb_internal():148] Internal process interrupted.
2021-09-11 12:44:54,454 INFO    SenderThread:10176 [sender.py:finish():979] shutting down sender
2021-09-11 12:44:54,454 INFO    WriterThread:10176 [datastore.py:close():281] close: C:\Programming\rl_cooperation\Pygame_RL_cooperation\wandb\offline-run-20210911_124436-6rxfhcbl\run-6rxfhcbl.wandb
2021-09-11 12:44:54,454 INFO    HandlerThread:10176 [handler.py:finish():683] shutting down handler
