2021-09-11 12:42:17,382 INFO    MainThread:12864 [internal.py:wandb_internal():86] W&B internal server running at pid: 12864, started at: 2021-09-11 12:42:17.373291
2021-09-11 12:42:17,383 INFO    WriterThread:12864 [datastore.py:open_for_write():77] open: C:\Programming\rl_cooperation\Pygame_RL_cooperation\wandb\offline-run-20210911_124216-18bkf2mr\run-18bkf2mr.wandb
2021-09-11 12:42:17,384 DEBUG   HandlerThread:12864 [handler.py:handle_request():126] handle_request: run_start
2021-09-11 12:42:17,401 DEBUG   HandlerThread:12864 [meta.py:__init__():40] meta init
2021-09-11 12:42:17,401 DEBUG   HandlerThread:12864 [meta.py:__init__():54] meta init done
2021-09-11 12:42:17,401 DEBUG   HandlerThread:12864 [meta.py:probe():211] probe
2021-09-11 12:42:17,467 DEBUG   HandlerThread:12864 [git.py:repo():33] git repository is invalid
2021-09-11 12:42:17,467 DEBUG   HandlerThread:12864 [meta.py:_save_pip():58] save pip
2021-09-11 12:42:17,468 DEBUG   HandlerThread:12864 [meta.py:_save_pip():72] save pip done
2021-09-11 12:42:17,468 DEBUG   HandlerThread:12864 [meta.py:probe():249] probe done
2021-09-11 12:42:23,405 WARNING MainThread:12864 [internal.py:wandb_internal():145] Internal process interrupt: 1
2021-09-11 12:42:23,632 WARNING MainThread:12864 [internal.py:wandb_internal():145] Internal process interrupt: 2
2021-09-11 12:42:23,632 ERROR   MainThread:12864 [internal.py:wandb_internal():148] Internal process interrupted.
2021-09-11 12:42:24,457 INFO    SenderThread:12864 [sender.py:finish():979] shutting down sender
2021-09-11 12:42:24,532 INFO    WriterThread:12864 [datastore.py:close():281] close: C:\Programming\rl_cooperation\Pygame_RL_cooperation\wandb\offline-run-20210911_124216-18bkf2mr\run-18bkf2mr.wandb
